# Default values for nodejsapp.
# Declare variables to be passed into your templates.

# Number of replicas to be deployed
replicaCount: 2

# Rolling Update strategy specifications
deployment:
  maxUnavailable: 1
  maxSurge: 1
  revisionHistoryLimit: 10
  minReadySeconds: 6
  terminationGracePeriodSeconds: 10

# Image details and pull policy
image:
  repository: jjjje/nodejsapp
  tag: latest
  pullPolicy: Always

# Container port specification for deployment
containerports:
  port1:
    name: nodejsport
    port: 8080
    protocol: TCP

# Image pull secrets and name overrides
imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

# Pod security context
podSecurityContext: {}
  # fsGroup: 2000

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Health check specifications  
livenessProbe:
  path: /health-check
  initialDelaySeconds: 10
  periodSeconds: 5
readinessProbe:
  path: /health-check
  initialDelaySeconds: 10
  periodSeconds: 5

# Service details  
service:
  type: NodePort
  port: 80
  nodeport: 30008

# Ingress details   
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
#   ingress.kubernetes.io/rewrite-target: /
#   nginx.ingress.kubernetes.io/rewrite-target: /
#   kubernetes.io/tls-acme: "true"
  hosts:
    - host: minikube.local
      paths: ["/"]

# TLS      
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Resources  
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
