---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "postgres.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/env: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volume.capacity.storage }} 
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes: {{ .Values.volume.accessModes }}
  hostPath:
    path: {{ .Values.volume.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgres.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/env: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volume.capacity.storage }}
  volumeName: {{ template "postgres.fullname" . }}-pv
  storageClassName: {{ .Values.volume.storageClassName }}
