apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}-credentials 
type: Opaque
data:
  db: {{ .Values.secret.db | b64enc | quote }}
  user: {{ .Values.secret.user | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
