apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/env: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  clusterIP: None
  name: postgresport 
  selector:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/env: {{ .Release.Namespace }} 
